### ISSUE TITLE
Move this project under k8s project

### ISSUE THREAD

**Issue by noorul** [kubernetes-el/kubernetes-el#110]
@chrisbarrett What do you think of moving this project under kubernetes umbrella. I am not sure whether this is possible. I would like to try. Do you have any reservations on this?

**Comment by noorul** [comment]
Looks like this is GPL-3 and k8s is Apache-2.0

**Comment by jinnovation** [comment]
@noorul: Doesn't sound like we have a clear path on this currently; shall we close this and re-open if/when it becomes relevant again?

**Comment by noorul** [comment]
@jinnovation Agreed! Closed!
