### ISSUE TITLE
How to edit deployments and other resources

### ISSUE THREAD

**Issue by MAliNaqvi** [kubernetes-el/kubernetes-el#124]
I am not able to find a way to edit my deployments on the fly. Is this capability implemented?

**Comment by noorul** [comment]
It is not implemented. If you are interested you can submit a PR.

**Comment by noorul** [comment]
@jinnovation I am trying to add this functionality.

**Comment by olymk2** [comment]
that would be awesome to see :)

**Comment by noorul** [comment]
This is partially fixed: Try edit pop-up key `E`

**Comment by zaks** [comment]
The edit pop-up key is not working for me. Emacs shows it's still bound to (evil-forward-WORD-end &optional COUNT). Surprisingly all other keys work. I'm using spacemacs.

**Comment by jinnovation** [comment]
@noorul: Shall we close this ticket again with @zaks's recent contribution?

**Comment by noorul** [comment]
@jinnovation I thought of implementing something like magit commit buffer with key bindings like C-c C-c and C-c C-k. I think we can close this and create a new enhancement ticket.
