### ISSUE TITLE
Web-based package documentation

### ISSUE THREAD

**Issue by jinnovation** [kubernetes-el/kubernetes-el#140]
This package might benefit from dedicated online documentation, akin to other prominent Emacs packages. Examples:
* [Projectile documentation](https://docs.projectile.mx/projectile/index.html)
* [emacs-lsp documentation](https://emacs-lsp.github.io/lsp-mode/)

**Comment by jinnovation** [comment]
This might be a good opportunity to recast our documentation around the [Divio documentation system](https://documentation.divio.com/).

**Comment by noorul** [comment]
How about mkdocs (https://www.mkdocs.org/) ?

**Comment by jinnovation** [comment]
> How about mkdocs (https://www.mkdocs.org/) ?

Great idea. In particular, [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/) is very popular and very full-featured.

**Comment by jinnovation** [comment]
Done; documentation is now accessible at https://kubernetes-el.github.io/kubernetes-el/
