### ISSUE TITLE
Obviate the magit dependency in favor of magit-section

### ISSUE THREAD

**Issue by jinnovation** [kubernetes-el/kubernetes-el#151]
This project uses Magit as a dependency primarily for the section capabilities. This is an extremely bulky dependency that previously I assume was unavoidable because the sectioning capabilities were coupled to Magit proper. However, Jonas has graciously [pulled `Magit-Section` into its own separate package](https://emacsair.me/2020/01/23/magit-section/) as of [Magit v3.0.0](https://github.com/magit/magit/blob/4a8646a30df99bbafc95d4f21a0b2bf0a6f6566f/Documentation/RelNotes/3.0.0.org#magit-v300-release-notes).

This project would benefit from removing the `magit` dependency entirely in favor of the new `magit-section`.

## Details

From a cursory look, we use `magit` in two places:
* `kubernetes-modes.el`
* `kubernetes-ast.el`

In the former, every `magit-` function referenced is a `magit-section-` function; this should be straightforward.

In the latter, I believe every `magit-` reference lines up with a counterpart in `magit-section`. The only one that I believe needs modification is the use of the `magit-header-line` face, which can presumably be easily swapped out for its parent face, `magit-section-heading`.

**Comment by noorul** [comment]
How about [tablist](https://github.com/politza/tablist) used by [docker.el](https://github.com/Silex/docker.el)

**Comment by jinnovation** [comment]
I have not used tablist or the [`tabulated-list-mode`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Tabulated-List-Mode.html) that it extends. However, a cursory look, e.g. at docker.el, suggests to me that it addresses a slightly different and much more specific use case than `kubernetes-el` addresses with magit-section. Specifically, `tabulated-list-mode` looks to specifically target the display of table-formatted data, which doesn't line up with how `kubernetes-el` structures its display of information.

Furthermore, it's worth noting that `kubernetes-el` *already uses* magit-section -- just getting it via the main `magit` package rather than the newly-released, targeted `magit-section` package -- which makes the transition to using `magit-section` directly comparatively very safe and non-disruptive.

I personally don't think tablist is relevant to `kubernetes-el` at this time. Let me know if you disagree.

**Comment by jinnovation** [comment]
I realize that this issue is blocked on #2.
