### ISSUE TITLE
Logs buffer overrides my key bindings

### ISSUE THREAD

**Issue by darabi** [kubernetes-el/kubernetes-el#161]
First, thank you for this package which is a great time-saver!

There is only one thing which is a bit annoying for me: when I fire up a `*kubernetes logs*` buffer, I cannot use my beloved `M-w` for  `kill-ring-save` as it is overwritten by `kubernetes-copy-thing-at-point` which doesn't seem to copy anything in the logs buffer. To copy, I have to use `C-insertchar` (is this a Windows default key?).

The same seems to be true for the `*kubernetes exec*` buffer.

I can of course modify the corresponding mode maps but is this intended behaviour or am I experiencing some problem?

Thank you

**Comment by noorul** [comment]
@darabi I also face the same issue and it is very annoying. I think we should not bind this in *log* and *exec* buffers.

@jinnovation What do you think?

**Comment by jinnovation** [comment]
If `kubernetes-copy-thing-at-point` is meaningless in log and exec buffers, I'm all for removing the `M-w` binding from those maps.

**Comment by noorul** [comment]
@darabi exec buffer is not derived from Kubernetes mode.

**Comment by darabi** [comment]
Wow, this was a fast reaction! Thank you.

Regarding the exec buffer, things are then probably more complicated: I cannot even use my `other-window (C-x o)` to escape from it :) I guess all keys are delivered to the process in the buffer in raw mode. This might be useful in certain settings, but not at all in others.

I will investigate a bit and open a new issue, when I know more about the problem.

Thanks again!

**Comment by noorul** [comment]
@darabi It is using `term-mode`.  Once you get used to https://www.gnu.org/software/emacs/manual/html_node/emacs/Term-Mode.html
