### ISSUE TITLE
Cache namespaces within the same session

### ISSUE THREAD

**Issue by jinnovation** [kubernetes-el/kubernetes-el#164]
I assume that it is extremely unlikely for the set of namespaces to change for a given session within the timeframe of a single "session" (defined as the time between `M-x kubernetes-overview` and `M-x kubernetes-kill-buffers`). During this time, each call to `kubernetes-set-namespace` fetches the namespace collection on every single call, which is laggy and results in a bad user experience.

While I don't think we necessarily need to cache context-namespaces pairs persistently across sessions, I think a good first step would be to cache the namespaces for a given context on first invocation of `kubernetes-set-namespace` within that kubectl context, and wipe that cache on "exit," i.e. death of all k8s buffers.

**Comment by noorul** [comment]
I would say, this is kind of related to #69. If we can move to k8s Informer as described in https://firehydrant.io/blog/dynamic-kubernetes-informers/ then we could solve most of the lag issues. Having said that the approach is not straightforward :(.

**Comment by noorul** [comment]
Looks like `kubectl` is also cache resources.

**Comment by jinnovation** [comment]
> Looks like kubectl also cache resources.

Good point. That being the case, I'm happy closing this until we have a more concrete need for revisiting.
