### ISSUE TITLE
How to view completed pods?

### ISSUE THREAD

**Issue by matthias-margush** [kubernetes-el/kubernetes-el#166]
When viewing pods, is there a way to display pods with status "Completed"? (Thanks for the great plugin!)

**Comment by noorul** [comment]
`kubectl` output has `Completed` state pods also. I wrote a quick test and found that somehow completed pods are getting filtered. Need to look further to understand whether it was intentional.

**Comment by noorul** [comment]
@matthias-margush I created a PR for this.
