### ISSUE TITLE
how to set the namespace for shared clusters manually?

### ISSUE THREAD

**Issue by timur-han** [kubernetes-el/kubernetes-el#185]
Hi all,

Thank you for the great contribution. 

On shared clusters, the get namespaces operation is not permitted for everyone. In such clusters, it will be useful to set the namespace manually. Is it possible currently?

Thank you!

**Comment by noorul** [comment]
What happens if you type a non-existent namespace in the list?

**Comment by timur-han** [comment]
I cannot type anything. It directly tries to fetch the list of namespaces and then I get an error. So I do not have a chance to set it

**Comment by noorul** [comment]
Can you share a screenshot?

**Comment by timur-han** [comment]
There is no meaningful screenshot I can share. The flow is like this:

1. M-x 
2. kubernetes-set-namespace

The result is like this then:
```
kubectl get namespaces -o json: Error from server (Forbidden): namespaces is forbidden: User "my-user" cannot list resource "namespaces" in API group "" at the cluster scope
```

**Comment by jinnovation** [comment]
This is related to #92. In that issue, I suggest allowing users to set explicit namespace lists to select from. The suggestion here to allow for explicitly setting namespace could coexist with that potentially.

**Comment by timur-han** [comment]
Ok thanks for pointing it out that's the feature I'm looking for
