### ISSUE TITLE
Requesting full edit access to this repo

### ISSUE THREAD

**Issue by jinnovation** [kubernetes-el/kubernetes-el#195]
@noorul, @chrisbarrett: I believe that there are still things that I, as a co-maintainer, can't do with this repo, e.g. access Settings to, say, enable [Discussions](https://docs.github.com/en/discussions) for the project as an alternative to open-ended issues. @noorul, I'm not sure if that's the case for you as well; could you confirm? 

Could we look into giving me and @noorul more comprehensive ownership permissions? @chrisbarrett, this would allow us to continue on the foundation you've laid out here without needing to nag you to do something that only you have access/permissions to.

**Comment by noorul** [comment]
@jinnovation  I invited you to be a member of the organization.

**Comment by jinnovation** [comment]
> @jinnovation  I invited you to be a member of the organization.

Thanks for this, can I be made an owner alongside you two?

**Comment by noorul** [comment]
@jinnovation Can you try now?

**Comment by jinnovation** [comment]
Looks good now, thanks a bunch.
