### ISSUE TITLE
Overview: Configmap display should show data

### ISSUE THREAD

**Issue by jinnovation** [kubernetes-el/kubernetes-el#199]
Currently, the display for ConfigMaps in `kubernetes-overview` simply shows the namespace and creation date, like so:
```
  metadata-grpc-configmap                            2    69d
    Namespace:  namespace
    Created:    2021-06-18T17:59:07Z
```

We could expand this to display the ConfigMap's data contents.

```
  metadata-grpc-configmap                            2    69d
    Namespace:  namespace
    Created:    2021-06-18T17:59:07Z
    Data: (2)
      HOST: localhost
      PORT: 8080
```

Care might be needed here for particularly large data entries, e.g. ConfigMaps that themselves contain entire text config files in a data entry. In such cases, we might display a truncated version.

**Comment by Walheimat** [comment]
I threw something together. If this looks okay to you, I'd also update/extend the tests.

Not sure if there's a better way to balance long key or value names.

So here any multi-line value is ellipsized twice using a new face that's even lighter using newline char.

https://user-images.githubusercontent.com/12915439/147132945-d72ff2c5-31cd-46a2-95fd-bc1845e22256.mp4

**Comment by jinnovation** [comment]
@Walheimat looks excellent, would love to see a PR with tests if you'd like to submit one.
