### ISSUE TITLE
underlying `kubectl` command goes into `sleep` in namespace with large number of pods

### ISSUE THREAD

**Issue by kavirajk** [kubernetes-el/kubernetes-el#218]
Every time I switch one particular namespace and try to get pods, entire emacs go hang.

Details:
`Kubernetes-Overview` -> c -> `change namespace` -> v -> `pods`

I see that the corresponding `kubectl` process goes into **sleep** status. NOTE: that namespace have around **800 pods**.

```
kavirajk  743407  683023  0 22:55 ?        00:00:02 /usr/bin/kubectl get pods -o json --namespace=<xxx>
```

Although if I try to execute same command in shell manually, it returns almost immediately.

Tried tracing that process to understand what `kubectl` is doing there. Looking like its doing `write()` and `futex()` calls repeatedly.

```
futex(0x560accd3ecb0, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
write(5, "\0", 1)                       = 1
futex(0x560accd3ecb0, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc000425150, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560accd3ecb0, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc000600150, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=743407, si_uid=1000} ---
rt_sigreturn({mask=[]})                 = 0
futex(0xc000078950, FUTEX_WAKE_PRIVATE, 1) = 1
getpid()                                = 743407
tgkill(743407, 743432, SIGURG)          = 0
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=743407, si_uid=1000} ---
rt_sigreturn({mask=[]})                 = 0
futex(0x560accd40af8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc000078950, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560accd3ecb0, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x560accd3ecb0, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
epoll_pwait(3, [], 128, 0, NULL, 0)     = 0
futex(0xc000078950, FUTEX_WAKE_PRIVATE, 1) = 1
getpid()                                = 743407
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=743407, si_uid=1000} ---
rt_sigreturn({mask=[]})                 = 743407
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=743407, si_uid=1000} ---
rt_sigreturn({mask=[]})                 = 743407
tgkill(743407, 743432, SIGURG)          = 0
futex(0xc000100550, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=743407, si_uid=1000} ---
rt_sigreturn({mask=[]})                 = 824633997744
futex(0x560accd40af8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x560accd409d8, FUTEX_WAKE_PRIVATE, 1) = 1

```

I love using `kubernetes-el` inside emacs. But using it on clusters with large number pods (in a single namespace) is making user experience not ideal.

Does anyone else face similar problems?

Any plans on using kubernetes informers? to avoid the performance problems? (not sure if its even possible with `kubectl` though.

Versions:
Emacs: 27.2
OS: Linux Manjaro (Kernel 5.13.19-2-MANJARO)

**Comment by noorul** [comment]
Did you try setting the following variables?

`kubernetes-poll-frequency` and `kubernetes-redraw-frequency`

**Comment by noorul** [comment]
There is a way to fix this as mentioned in the README.md. Closing this ticket for inactivity. Please re-open as needed.
