### ISSUE TITLE
Make kubernetes resource `copiable` after `kubernetes-navigate` to it

### ISSUE THREAD

**Issue by kavirajk** [kubernetes-el/kubernetes-el#219]
After `kubernetes-navigate` to specific resource, I should be able to copy it. 

Now when I try to select the region and do `M-w` (`kubernetes-copy-thing-at-point`) it doesn't copy anything. Currently only way to copy is to go to Edit mode and copy it (which may be unsafe in some cases).

**Comment by noorul** [comment]
Is this not working for all the resources?

**Comment by noorul** [comment]
M-w is bound to `kubernetes-copy-thing-at-point` which is a feature.
