### ISSUE TITLE
Support specifying namespace when using Tramp mode

### ISSUE THREAD

**Issue by neutrous** [kubernetes-el/kubernetes-el#264]
Really appreciated this wonderful project, I'm using this quite often every day to help me manage the cluster.

However, using Tramp mode to view Pods/Containers files is not supported well at the moment if different namespaces are involved. Didn't find a way to properly pass the namespace parameter yet.

**Comment by noorul** [comment]
I think what we could do is to execute ```kubectl config set-context --current --namespace=<insert-namespace-name-here>``` when a user switches to a particular namespace.
