### ISSUE TITLE
Cyclic dependency of `kubernetes-core` and `kubernetes-utils`

### ISSUE THREAD

**Issue by nagy** [kubernetes-el/kubernetes-el#265]
The file `kubernetes-core.el` uses the macro `kubernetes-utils--save-window-state` inside of the function `kubernetes--redraw-overview-buffer` , but this macro is defined in `kubernetes-utils`, which itself depends on `kubernetes-core`. This can lead to the function being wrongfully evaluated if the utils file has not been loaded otherwise.

Maybe we need to move ( and rename ) the macro to somewhere else.

**Comment by nagy** [comment]
I ran into this occasionally, that's why I investigated, but I cannot reproduce this right now. What has helped me was to put the macro definition in my `use-package` config like so:

```elisp
(use-package kubernetes
  :init
  (defmacro kubernetes-utils--save-window-state (&rest body)
    `(let ((pos (point)) (col (current-column)) (window-start-line (window-start)) (inhibit-redisplay t))
       (save-excursion ,@body)
       (goto-char pos)
       (move-to-column col)
       (set-window-start (selected-window) window-start-line)))
  ;; ..
)
```

**Comment by sfdc-slumos** [comment]
I think this is why I am unable to `M-x kubernetes-overview` due to `Error running timer ‘kubernetes-state-trigger-redraw’: (invalid-function kubernetes-utils--save-window-state)`. Will try the workaround.

**Comment by slumos** [comment]
I think this is why I am unable to `M-x kubernetes-overview` due to `Error running timer ‘kubernetes-state-trigger-redraw’: (invalid-function kubernetes-utils--save-window-state)`. Will try the workaround.

**Comment by nagy** [comment]
That `(invalid-function kubernetes-utils--save-window-state)` part is exactly what I got as well. Keep in mind that you need to reevaluate `kubernetes--redraw-overview-buffer` because it would have used that macro at its evaluation time, but it couldnt. Or just restart emacs.

**Comment by sfdc-slumos** [comment]
Restarted and even `rm *elc` in the package directory, but what I did not do was `rm kube*eln` in the eln-cache. Now it works.

**Comment by karmajunkie** [comment]
Same problem and solution here with doom. Removing the eln cache was essential.

**Comment by 404cn** [comment]
Is there any fix for this issue? This package is completely unusable for me.

**Comment by noorul** [comment]
Did you try above suggestions? Remove kubernetes related eln cache?

**Comment by jinnovation** [comment]
@nagy: I believe I have a way to circumvent this issue entirely with #278. Please take a look.
