### ISSUE TITLE
Feat Request: timestamp flag in `kubernetes-log`

### ISSUE THREAD

**Issue by danilevy1212** [kubernetes-el/kubernetes-el#270]
First of all, thanks a lot for this super useful and awesome package,

In our clusters we don't spawn logs that are timestamped, we use the `--timestamp` flag so kubernetes adds the timestamp for us. Sadly, this options doesn't exist for kubernetes-el, which forces me sometimes to use the terminal instead of this package. Would it be possible to add this `--timestamp` flag to `kubernetes-logs`?

![image](https://user-images.githubusercontent.com/32525865/160874373-238a9ce9-6627-4276-9c48-eaad75c6512d.png)

**Comment by noorul** [comment]
@danilevy1212 This is implemented

**Comment by danilevy1212** [comment]
Thank you so much! @noorul
