### ISSUE TITLE
Macro `kubernetes--save-window-state` leads to issues on Emacs 29.x

### ISSUE THREAD

**Issue by Walheimat** [kubernetes-el/kubernetes-el#295]
There's a function in `kubernetes-core.el` defined as a macro that leads to problems. I assume this is a Emacs 28 and up problem as I'm surprised to not find an open issue for this.

My current workaround is to redefine the symbol as a normal function:

```elisp
(defun kubernetes--save-window-state (&rest body)
  "Restore window state after executing BODY.

This is an exact copy of the original function which was defined
as a macro."
  (let ((pos (point))
        (col (current-column))
        (window-start-line (window-start))
        (inhibit-redisplay t))
    (save-excursion
      ',@body)
    (goto-char pos)
    (move-to-column col)
    (set-window-start (selected-window) window-start-line)))
```

I just noticed this again because I think it used to be `kubernetes-utils--save-window-state` and I was overriding that one. Updating the view doesn't work because of this function.

If there's no additional reason why this is defined as a macro instead, maybe it could be replaced by the function version? I didn't open an MR because I'm assuming there is good reason for this.

Maybe interesting tidbit: The byte compiler also complains about the macro saying: "macro `kubernetes--save-window-state` defined too late".

**Comment by jinnovation** [comment]
> leads to problems

Can you be more specific?

> I just noticed this again because I think it used to be `kubernetes-utils--save-window-state`

Yup, we renamed this in #278 in response to #265.

> If there's no additional reason why this is defined as a macro instead, maybe it could be replaced by the function version? 

This sounds perfectly reasonable, I don't see any particular reason this needs to be a macro either.

> I didn't open an MR...

Please do; @noorul and I would be more than happy to review.

> ...because I'm assuming there is good reason for this.

Eh, there are several instances of IMO overzealous macro usage in the codebase. This is one of them.

**Comment by Walheimat** [comment]
I'll open a PR.

Basically it breaks refreshing the overview buffer, meaning you can't do anything outside of what's presented initially.

**Comment by jinnovation** [comment]
Thanks, I see #303 now. 

Also to clarify: what Emacs version are you seeing these refresh/redraw issues in? You call out 29.x in #303; is this issue, as far as you can tell, limited to 29.x?

**Comment by jinnovation** [comment]
> I guess I could test if this is also an issue in 28 but I can't say when I have time to build and test this.

Not a huge deal if you don't have the time to look into it. I'll recast this issue to be specific to 29.x and if it surfaces in 28.x for anyone we'll revisit.
