### ISSUE TITLE
Implement dynamic downloading of Go binary

### ISSUE THREAD

**Issue by chrisbarrett** [kubernetes-el/kubernetes-el#42]
At runtime,  we should test whether the go server exists, and download it if not.

**Comment by jinnovation** [comment]
@noorul, @chrisbarrett: Thoughts on closing this ticket, w/ the understanding that we can easily reopen if/when we ever decide to seriously reopen the conversation around Go backend?

**Comment by noorul** [comment]
Let us close this for now.
