### ISSUE TITLE
Propagate kubectl settings through exec commands

### ISSUE THREAD

**Issue by jackelliott** [kubernetes-el/kubernetes-el#64]
Currently, the kubectl exec popup ignores the configuration popup's KUBECONFIG setting. 

This means that when execing into pods, we will fail if we need to use a non-default kubeconfig file.

Setting this to point to a file will only update the configurations window (which will work fine). When running the exec commands, we can see all the running pods, but the actual exec command will not run with the --kubeconfig option enabled. 

I fix this in my own environment by adding 
      (push '"--kubeconfig=/path/to/my/kubecofig/kubeconfig.yaml" args)
at line 121 .... But there must be a better way!
Rocking package, by the way! I'm the envy of the office!

**Comment by chrisbarrett** [comment]
Thanks for the positive feedback. :) 

Right now I'm focusing my efforts on integrating with a custom Go client to offload work from Emacs, which means it might take a while for me to get to this ticket. Sounds like you've got a working hack, so that's good. 👍

**Comment by noorul** [comment]
This is fixed!
