### ISSUE TITLE
Get logs from multiple containers

### ISSUE THREAD

**Issue by paulbdavis** [kubernetes-el/kubernetes-el#70]
Would it be possible to add the ability to stream/read logs from all containers in a pod at once?

**Comment by peterbecich** [comment]
Perhaps implementation would be easier to give each `*kubernetes logs*` buffer a distinct name, so more than one can be opened.  Thank you.

**Comment by jinnovation** [comment]
Kubetail looks to be for streaming logs from multiple pods. While I'm ambivalent about the need for that functionality, I'll point out that this ticket specifically is concerned with multiple/all containers from the same pod.

The `--all-containers` flag for `kubectl logs` should be useful here.

**Comment by noorul** [comment]
This is implemented via https://github.com/kubernetes-el/kubernetes-el/pull/160

**Comment by jinnovation** [comment]
Excellent, shall we consider this issue closed then?

**Comment by noorul** [comment]
I think so as we are not planning to support third party tools now.
