### ISSUE TITLE
Support using kubectl through SSH

### ISSUE THREAD

**Issue by SerialVelocity** [kubernetes-el/kubernetes-el#71]
It would be nice to support running kubectl through tramp.

Use-case: Kubernetes is isolated from the internet. You need to ssh in to a cluster to get access.

**Comment by noorul** [comment]
I think it is possible to create a wrapper command and use it. See variable kubernetes-kubectl-executable.

**Comment by SerialVelocity** [comment]
It's also possible to do it via port forwarding. I was just hoping to be able to pass in a tramp style URL or something (I stopped using this quite a while ago so I can't remember how it is configured) since I was running this against a group of remote kubernetes clusters

**Comment by noorul** [comment]
Customize variable `kubernetes-kubectl-executable` to point to a wrapper that will do the heavy lifting.
