### ISSUE TITLE
kubeconfig not passed to logging command

### ISSUE THREAD

**Issue by SerialVelocity** [kubernetes-el/kubernetes-el#73]
Hey,

When I press try to open the logs of a pod (`l l`) on the pods view (`v pods <enter>`), it is trying to run:
```
kubectl logs <container name> --namespace=
```
instead of:
```
kubectl --kubeconfig=<my config> logs <container name> --namespace=
```

Probably the same as #64 but for logging instead of exec

P.S. The namespace is blank there because it is trying to use the namespace set in config rather than the namespace of the selected pod and I have a workaround so I can see pods in all namespaces

**Comment by ageekymonk** [comment]
@SerialVelocity Do you still see the issue ?

**Comment by SerialVelocity** [comment]
Hey @ageekymonk, I'm on 0.12.0 (melpa-stable) and still see the issue

**Comment by noorul** [comment]
@chrisbarrett What is the release process for melpa and melpa stable?

**Comment by chrisbarrett** [comment]
Melpa builds whatever's merged to master at regular intervals. Melpa stable only builds when you push a new git tag.

**Comment by noorul** [comment]
Latest version should not have this issue.
