### ISSUE TITLE
doc: Include Patreon link? 

### ISSUE THREAD

**Issue by adamdecaf** [kubernetes-el/kubernetes-el#91]
Hey! I love using this project and think you should put up a Patreon (or others [BuyMeACoffee](https://www.buymeacoffee.com/)). 

It's another way of saying thanks for making something so cool!

**Comment by chrisbarrett** [comment]
Aaaaw, thanks for the kind words! 😄 I've got a bit of guilt for not really working on this package for a year, but maybe coffees would be a good signal to see whether people are getting value. Thanks for the suggestion, I'll ponder on it!

**Comment by jinnovation** [comment]
Going to close this out as a stale issue that's also slightly complicated by multiple people maintaining and actively working on this project now.

@chrisbarrett: feel free to reopen if you end up deciding you're interested in free internet ☕.
